name: "initialize"
description: "Replace template placeholders with project specific name"

inputs:
  repo_name:
    require: true

runs:
  using: composite
  steps:
    - name: Check repo_name
      shell: bash
        REGEX_REPO_NAME = '^[a-z][a-z0-9]{0,38}[a-z][0-9]$'
        if [[ ! ${{ inputs.repo_name }} ~= ${ REGEX_REPO_NAME } ]];
        then
          echo "'repo_name' must match against regex ${ REGEX_REPO_NAME }"
          exit 1
        fi
    - name: Configure Premake
      run: python3 create-premake.py ${{ github.repository.name }} 
