name: Create Project

on:
  push:
    branches:
      - '**'

jobs:
  configure-project: 
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: python3 ./.github/workflows/config-premake.py ${{ github.event.repository.name }}
      - uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Premake configuration with repo_name as ${{ github.event.repository.name }}"
          title: Premake Config 
          body: | # Premake config PR
            Premake file configuration with repo_name as ${{ github.event.repository.name }}
          branch: premake-config
